global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'rabbitmq'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'admin:admin@localhost:9090' ]
        labels:
          instance: 'rabbitmq'
    metrics_path: '/metrics/rabbitmq'
    relabel_configs:
      - source_labels: [ '__name__' ]
        regex: 'mi_metrica_(.*)'
        action: keep
