global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['flask:5000']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    metrics_path: /api/metrics
    basic_auth:
      username: ${RABBITMQ_USER}
      password: ${RABBITMQ_PASSWORD}
